//var msgrec = require('./js/recarga.js');
//var msghum = require('./js/humidity.js');
//var msgele = require('./js/elevation.js');
//var msgpre = require('./js/pressure.js');
var msgtem = require('./js/temperature.js');
//var msginf = require('./js/infraestructura.js');
//var msgflo = require('./js/flow.js');
//setInterval(msgrec.msgrecarga, 5000);
//setInterval(msghum.msghumidity,5000);
//setInterval(msgele.msgelevation,5000);
//setInterval(msgpre.msgpressure, 5000);
setInterval(msgtem.msgtemperature,5000);
//setInterval(msginf.msginfraestructura,5000);
//setInterval(msgflo.msgflow, 5000);
