var msghum = require('./js/humidity.js');
var msgele = require('./js/elevation.js');
var msgpre = require('./js/pressure.js');
var msgtem = require('./js/temperature.js');
var msgflo = require('./js/flow.js');
setInterval(msghum.msghumidity,5000);
setInterval(msgele.msgelevation,5000);
setInterval(msgpre.msgpressure, 5000);
setInterval(msgtem.msgtemperature,5000);
setInterval(msgflo.msgflow, 5000);
